import { GlEmptyState, GlButton, GlBadge } from '@gitlab/ui';
import { nextTick } from 'vue';
import AiGenieLoader from 'ee/ai/components/ai_genie_loader.vue';
import AiGenieChat from 'ee/ai/components/ai_genie_chat.vue';
import AiPredefinedPrompts from 'ee/ai/components/ai_predefined_prompts.vue';
import { shallowMountExtended } from 'helpers/vue_test_utils_helper';
import { i18n, GENIE_CHAT_MODEL_ROLES } from 'ee/ai/constants';

describe('AiGenieChat', () => {
  let wrapper;

  const createComponent = ({ propsData = {}, data = {}, scopedSlots = {}, slots = {} } = {}) => {
    wrapper = shallowMountExtended(AiGenieChat, {
      propsData,
      data() {
        return {
          ...data,
        };
      },
      scopedSlots,
      slots,
      stubs: {
        AiGenieLoader,
      },
    });
  };

  const findChatComponent = () => wrapper.findByTestId('chat-component');
  const findCloseButton = () => wrapper.findComponent(GlButton);
  const findCustomLoader = () => wrapper.findComponent(AiGenieLoader);
  const findChatMessages = () => wrapper.findAll('.ai-genie-chat-message');
  const findError = () => wrapper.findByTestId('chat-error');
  const findFooter = () => wrapper.findByTestId('chat-footer');
  const findGeneratedByAI = () => wrapper.findByText(i18n.GENIE_CHAT_LEGAL_GENERATED_BY_AI);
  const findBadge = () => wrapper.findComponent(GlBadge);
  const findEmptyState = () => wrapper.findComponent(GlEmptyState);
  const findPredefined = () => wrapper.findComponent(AiPredefinedPrompts);
  const findChatInput = () => wrapper.findByTestId('chat-prompt-input');
  const findCloseChatButton = () => wrapper.findByTestId('chat-close-button');
  const findLegalDisclaimer = () => wrapper.findByTestId('chat-legal-disclaimer');

  beforeEach(() => {
    createComponent();
  });

  const promptStr = 'foo';
  const messages = [
    {
      role: GENIE_CHAT_MODEL_ROLES.user,
      content: promptStr,
    },
  ];

  describe('rendering', () => {
    it.each`
      desc                                  | component            | shouldRender
      ${'renders root component'}           | ${findChatComponent} | ${true}
      ${'renders experimental label'}       | ${findBadge}         | ${true}
      ${'renders empty state'}              | ${findEmptyState}    | ${true}
      ${'renders predefined prompts'}       | ${findPredefined}    | ${true}
      ${'does not render loading skeleton'} | ${findCustomLoader}  | ${false}
      ${'does not render chat error'}       | ${findError}         | ${false}
      ${'does not render chat input'}       | ${findChatInput}     | ${false}
      ${'renders a generated by AI note'}   | ${findGeneratedByAI} | ${true}
    `('$desc', ({ component, shouldRender }) => {
      expect(component().exists()).toBe(shouldRender);
    });

    describe('when messages exist', () => {
      it('scrolls to the bottom on load', async () => {
        createComponent({ propsData: { messages } });
        const { element } = findChatComponent();
        jest.spyOn(element, 'scrollHeight', 'get').mockReturnValue(200);

        await nextTick();

        expect(element.scrollTop).toEqual(200);
      });
    });

    describe('slots', () => {
      const slotContent = 'As Gregor Samsa awoke one morning from uneasy dreams';

      describe('the feedback slot', () => {
        const slotElement = `<template>${slotContent}</template>`;

        it.each(['assistant', 'ASSISTANT'])(
          'renders the content passed to the "feedback" slot when role is %s',
          (role) => {
            createComponent({
              propsData: {
                messages: [
                  {
                    role: GENIE_CHAT_MODEL_ROLES.user,
                    content: 'User foo',
                  },
                  {
                    role,
                    content: 'Assistent bar',
                  },
                ],
              },
              scopedSlots: { feedback: slotElement },
            });
            expect(findChatMessages().at(0).text()).not.toContain(slotContent);
            expect(findChatMessages().at(1).text()).toContain(slotContent);
          },
        );

        it('sends correct `message` in the `slotProps` for the components users to consume', () => {
          createComponent({
            propsData: {
              messages: [
                {
                  role: GENIE_CHAT_MODEL_ROLES.assistant,
                  content: slotContent,
                },
              ],
            },
            scopedSlots: {
              feedback: `<template #feedback="slotProps">
              Hello {{ slotProps.message.content }}
              </template>
            `,
            },
          });
          expect(wrapper.text()).toContain(`Hello ${slotContent}`);
        });
      });

      it.each`
        desc                 | slot           | content        | isChatAvailable | shouldRenderSlotContent
        ${'renders'}         | ${'hero'}      | ${slotContent} | ${true}         | ${true}
        ${'renders'}         | ${'hero'}      | ${slotContent} | ${false}        | ${true}
        ${'does not render'} | ${'subheader'} | ${slotContent} | ${false}        | ${true}
        ${'renders'}         | ${'subheader'} | ${slotContent} | ${true}         | ${true}
      `(
        '$desc the $content passed to the $slot slot when isChatAvailable is $isChatAvailable',
        ({ slot, content, isChatAvailable, shouldRenderSlotContent }) => {
          createComponent({
            propsData: { isChatAvailable },
            slots: { [slot]: content },
          });
          if (shouldRenderSlotContent) {
            expect(wrapper.text()).toContain(content);
          } else {
            expect(wrapper.text()).not.toContain(content);
          }
        },
      );
    });

    it('sets correct props on the Experiment label', () => {
      const badgeType = 'neutral';
      const badgeSize = 'md';
      expect(findBadge().props('variant')).toBe(badgeType);
      expect(findBadge().props('size')).toBe(badgeSize);
      expect(findBadge().text()).toBe(i18n.EXPERIMENT_BADGE);
    });
  });

  describe('interaction', () => {
    it('is hidden after the header button is clicked', async () => {
      findCloseButton().vm.$emit('click');
      await nextTick();
      expect(findChatComponent().exists()).toBe(false);
    });

    it('resets the hidden status of the component on loading', async () => {
      createComponent({ data: { isHidden: true } });
      expect(findChatComponent().exists()).toBe(false);
      // setProps is justified here because we are testing the component's
      // reactive behavior which consistutes an exception
      // See https://docs.gitlab.com/ee/development/fe_guide/style/vue.html#setting-component-state
      wrapper.setProps({
        isLoading: true,
      });
      await nextTick();
      expect(findChatComponent().exists()).toBe(true);
    });

    it('renders custom loader when isLoading', () => {
      createComponent({ propsData: { isLoading: true } });
      expect(findCustomLoader().exists()).toBe(true);
    });

    it('renders alert if error', () => {
      const errorMessage = 'Something went Wrong';
      createComponent({ propsData: { error: errorMessage } });
      expect(findError().text()).toBe(errorMessage);
    });

    it('renders messages when messages are passed', () => {
      createComponent({ propsData: { messages } });
      expect(findChatMessages().at(0).text()).toBe(promptStr);
    });

    it('converts content of the message from Markdown into HTML', () => {
      createComponent({
        propsData: {
          messages: [
            {
              role: GENIE_CHAT_MODEL_ROLES.user,
              content: '**foo**',
            },
          ],
        },
      });
      expect(findChatMessages().at(0).element.innerHTML).toContain('<strong>foo</strong>');
    });

    it('hides the chat on button click and emits an event', () => {
      createComponent({ propsData: { messages } });
      expect(wrapper.vm.$data.isHidden).toBe(false);
      findCloseChatButton().vm.$emit('click');
      expect(wrapper.vm.$data.isHidden).toBe(true);
      expect(wrapper.emitted('chat-hidden')).toBeDefined();
    });

    it('does not render the empty state when there are messages available', () => {
      createComponent({ propsData: { messages } });
      expect(findEmptyState().exists()).toBe(false);
    });

    describe('chat', () => {
      it('does not render prompt input by default', () => {
        createComponent({ propsData: { messages } });
        expect(findChatInput().exists()).toBe(false);
      });

      it('renders prompt input if `isChatAvailable` prop is `true`', () => {
        createComponent({ propsData: { messages, isChatAvailable: true } });
        expect(findChatInput().exists()).toBe(true);
      });

      it('renders the legal disclaimer if `isChatAvailable` prop is `true', () => {
        createComponent({ propsData: { messages, isChatAvailable: true } });
        expect(findLegalDisclaimer().exists()).toBe(true);
      });
    });

    describe('scrolling', () => {
      let element;

      beforeEach(() => {
        createComponent({ propsData: { messages, isChatAvailable: true } });
        element = findChatComponent().element;
      });

      it('when scrolling to the bottom it removes the scrim class', async () => {
        jest.spyOn(element, 'scrollTop', 'get').mockReturnValue(100);
        jest.spyOn(element, 'offsetHeight', 'get').mockReturnValue(100);
        jest.spyOn(element, 'scrollHeight', 'get').mockReturnValue(200);

        findChatComponent().trigger('scroll');

        await nextTick();

        expect(findFooter().classes()).not.toContain('gl-drawer-body-scrim-on-footer');
      });

      it('when scrolling up it adds the scrim class', async () => {
        jest.spyOn(element, 'scrollTop', 'get').mockReturnValue(50);
        jest.spyOn(element, 'offsetHeight', 'get').mockReturnValue(100);
        jest.spyOn(element, 'scrollHeight', 'get').mockReturnValue(200);

        findChatComponent().trigger('scroll');

        await nextTick();

        expect(findFooter().classes()).toContain('gl-drawer-body-scrim-on-footer');
      });
    });

    describe('predefined prompts', () => {
      const prompts = ['what is a fork'];

      beforeEach(() => {
        createComponent({ propsData: { predefinedPrompts: prompts } });
      });

      it('passes on predefined prompts', () => {
        expect(findPredefined().props().prompts).toEqual(prompts);
      });

      it('listens to the click event and sends the predefined prompt', async () => {
        findPredefined().vm.$emit('click', prompts[0]);

        await nextTick();

        expect(wrapper.emitted('send-chat-prompt')).toEqual([[prompts[0]]]);
      });
    });
  });
});
