export const mockResultSet = {
  seriesNames: () => [
    {
      title: 'pageview, Jitsu Count',
      key: 'pageview,Jitsu.count',
      yValues: ['pageview', 'Jitsu.count'],
    },
  ],
  chartPivot: () => [
    {
      x: '2022-11-09T00:00:00.000',
      xValues: ['2022-11-09T00:00:00.000'],
      'pageview,Jitsu.count': 55,
    },
    {
      x: '2022-11-10T00:00:00.000',
      xValues: ['2022-11-10T00:00:00.000'],
      'pageview,Jitsu.count': 14,
    },
  ],
  tableColumns: () => [
    {
      key: 'Jitsu.utcTime.day',
      title: 'Jitsu Utc Time',
      shortTitle: 'Utc Time',
      type: 'time',
      dataIndex: 'Jitsu.utcTime.day',
    },
    {
      key: 'Jitsu.eventType',
      title: 'Jitsu Event Type',
      shortTitle: 'Event Type',
      type: 'string',
      dataIndex: 'Jitsu.eventType',
    },
    {
      key: 'Jitsu.count',
      type: 'number',
      dataIndex: 'Jitsu.count',
      title: 'Jitsu Count',
      shortTitle: 'Count',
    },
  ],
  tablePivot: () => [
    {
      'Jitsu.utcTime.day': '2022-11-09T00:00:00.000',
      'Jitsu.eventType': 'pageview',
      'Jitsu.count': '55',
    },
    {
      'Jitsu.utcTime.day': '2022-11-10T00:00:00.000',
      'Jitsu.eventType': 'pageview',
      'Jitsu.count': '14',
    },
  ],
  rawData: () => [
    {
      'Jitsu.userLanguage': 'en-US',
      'Jitsu.count': '36',
      'Jitsu.url': 'https://example.com/us',
    },
    {
      'Jitsu.userLanguage': 'es-ES',
      'Jitsu.count': '60',
      'Jitsu.url': 'https://example.com/es',
    },
  ],
};

export const mockCountResultSet = (count) => ({
  rawData: () => [
    {
      'Jitsu.count': count,
    },
  ],
});

export const mockMetaData = {
  cubes: [
    {
      name: 'Jitsu',
      title: 'Jitsu',
      measures: [
        {
          name: 'Jitsu.count',
          title: 'Jitsu Count',
          shortTitle: 'Count',
          cumulativeTotal: false,
          cumulative: false,
          type: 'number',
          aggType: 'count',
          drillMembers: [
            'Jitsu.eventnCtxEventId',
            'Jitsu.idsAjsAnonymousId',
            'Jitsu.pageTitle',
            'Jitsu.userAnonymousId',
            'Jitsu.userHashedAnonymousId',
          ],
          drillMembersGrouped: {
            measures: [],
            dimensions: [
              'Jitsu.eventnCtxEventId',
              'Jitsu.idsAjsAnonymousId',
              'Jitsu.pageTitle',
              'Jitsu.userAnonymousId',
              'Jitsu.userHashedAnonymousId',
            ],
          },
          isVisible: true,
        },
      ],
      dimensions: [
        {
          name: 'Jitsu.apiKey',
          title: 'Jitsu Api Key',
          type: 'string',
          shortTitle: 'Api Key',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.docEncoding',
          title: 'Jitsu Doc Encoding',
          type: 'string',
          shortTitle: 'Doc Encoding',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.docHost',
          title: 'Jitsu Doc Host',
          type: 'string',
          shortTitle: 'Doc Host',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.docPath',
          title: 'Jitsu Doc Path',
          type: 'string',
          shortTitle: 'Doc Path',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.docSearch',
          title: 'Jitsu Doc Search',
          type: 'string',
          shortTitle: 'Doc Search',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.eventType',
          title: 'Jitsu Event Type',
          type: 'string',
          shortTitle: 'Event Type',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.eventnCtxEventId',
          title: 'Jitsu Eventn Ctx Event Id',
          type: 'string',
          shortTitle: 'Eventn Ctx Event Id',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.idsAjsAnonymousId',
          title: 'Jitsu Ids Ajs Anonymous Id',
          type: 'string',
          shortTitle: 'Ids Ajs Anonymous Id',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.localTzOffset',
          title: 'Jitsu Local Tz Offset',
          type: 'string',
          shortTitle: 'Local Tz Offset',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.pageTitle',
          title: 'Jitsu Page Title',
          type: 'string',
          shortTitle: 'Page Title',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.parsedUaOsFamily',
          title: 'Jitsu Parsed Ua Os Family',
          type: 'string',
          shortTitle: 'Parsed Ua Os Family',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.parsedUaOsVersion',
          title: 'Jitsu Parsed Ua Os Version',
          type: 'string',
          shortTitle: 'Parsed Ua Os Version',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.parsedUaUaFamily',
          title: 'Jitsu Parsed Ua Ua Family',
          type: 'string',
          shortTitle: 'Parsed Ua Ua Family',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.parsedUaUaVersion',
          title: 'Jitsu Parsed Ua Ua Version',
          type: 'string',
          shortTitle: 'Parsed Ua Ua Version',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.referer',
          title: 'Jitsu Referer',
          type: 'string',
          shortTitle: 'Referer',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.screenResolution',
          title: 'Jitsu Screen Resolution',
          type: 'string',
          shortTitle: 'Screen Resolution',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.sourceIp',
          title: 'Jitsu Source Ip',
          type: 'string',
          shortTitle: 'Source Ip',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.src',
          title: 'Jitsu Src',
          type: 'string',
          shortTitle: 'Src',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.url',
          title: 'Jitsu Url',
          type: 'string',
          shortTitle: 'Url',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.userAgent',
          title: 'Jitsu User Agent',
          type: 'string',
          shortTitle: 'User Agent',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.userAnonymousId',
          title: 'Jitsu User Anonymous Id',
          type: 'string',
          shortTitle: 'User Anonymous Id',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.userHashedAnonymousId',
          title: 'Jitsu User Hashed Anonymous Id',
          type: 'string',
          shortTitle: 'User Hashed Anonymous Id',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.userLanguage',
          title: 'Jitsu User Language',
          type: 'string',
          shortTitle: 'User Language',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.vpSize',
          title: 'Jitsu Vp Size',
          type: 'string',
          shortTitle: 'Vp Size',
          suggestFilterValues: true,
          isVisible: true,
        },
        {
          name: 'Jitsu.utcTime',
          title: 'Jitsu Utc Time',
          type: 'time',
          shortTitle: 'Utc Time',
          suggestFilterValues: true,
          isVisible: true,
        },
      ],
      segments: [],
    },
  ],
};
