// Fixtures generated by: spec/frontend/fixtures/runner.rb

// List queries
import allRunnersUpgradeStatusData from 'test_fixtures/graphql/runner/list/all_runners.query.graphql.upgrade_status.json';

export { allRunnersUpgradeStatusData };
