// Fixtures generated by: spec/frontend/fixtures/runner.rb

// List queries
import allRunnersUpgradeStatusData from 'test_fixtures/graphql/ci/runner/list/all_runners.query.graphql.upgrade_status.json';

// Dashboard queries
import mostActiveRunnersData from 'test_fixtures/graphql/ci/runner/performance/most_active_runners.graphql.json';

export { allRunnersUpgradeStatusData, mostActiveRunnersData };
