#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative '../config/bundler_setup'

require 'request_store'
require 'rake'
require 'rails/autoloaders/inflector'
require 'active_support/dependencies/autoload'
require 'active_support/core_ext/numeric'
require 'active_support/string_inquirer'
require 'zeitwerk'

ENV['SKIP_RAILS_ENV_IN_RAKE'] = 'true'

module Rails
  extend self

  def root
    Pathname.new(File.expand_path('..', __dir__))
  end

  def env
    @_env ||= ActiveSupport::StringInquirer.new(ENV["RAILS_ENV"] || ENV["RACK_ENV"] || "test")
  end

  def autoloaders
    @autoloaders ||= [
      Zeitwerk::Loader.new.tap do |loader|
        loader.inflector = Rails::Autoloaders::Inflector
      end
    ]
  end
end

load File.expand_path('../lib/tasks/gitlab/helpers.rake', __dir__)
load File.expand_path('../lib/tasks/gitlab/gitaly.rake', __dir__)

# Required for config/0_inject_enterprise_edition_module.rb, lib/gitlab/access.rb
require File.expand_path('../lib/gitlab', __dir__)

require File.expand_path('../config/initializers/0_inject_enterprise_edition_module', __dir__)
require File.expand_path('../config/initializers_before_autoloader/004_zeitwerk', __dir__)

Rails.autoloaders.each do |autoloader|
  autoloader.push_dir('lib')
  autoloader.setup
end

# Require for lib/gitlab/gitaly_client/storage_settings.rb and config/initializers/1_settings.rb
require 'active_support/hash_with_indifferent_access'

# Required for lib/gitlab/visibility_level.rb and lib/gitlab/safe_request_store.rb
require 'active_support/concern'
require 'active_support/core_ext/module/delegation'

# Required for lib/system_check/helpers.rb
require File.expand_path('../lib/gitlab/task_helpers', __dir__)

# Required for lib/tasks/gitlab/helpers.rake
require File.expand_path('../lib/system_check/helpers', __dir__)

# Required for config/initializers/1_settings.rb
require 'omniauth'
require 'omniauth-github'
require 'etc'
require File.expand_path('../lib/gitlab/access', __dir__)
require File.expand_path('../lib/gitlab/utils', __dir__)

require File.expand_path('../config/initializers/1_settings', __dir__)

Gitlab.ee do
  load File.expand_path('../ee/lib/tasks/gitlab/indexer.rake', __dir__)

  require File.expand_path('../ee/lib/gitlab/elastic/indexer', __dir__)
  require File.expand_path('../lib/gitlab/utils/override', __dir__)
end

require File.expand_path('../spec/support/helpers/test_env', __dir__)

TestEnv.init
