.bundle/
danger/
doc/
log/*.log
node_modules/
rubocop/
tmp/*

db/fixtures/
!db/fixtures/development/01_admin.rb
!db/fixtures/development/02_application_settings.rb
!db/fixtures/development/25_api_personal_access_token.rb

ee/db/fixtures/
!ee/db/fixtures/development/10_license_file.rb

qa/
!qa/gdk

rubocop/

scripts/
!scripts/frontend

spec/
# Required by ee/lib/tasks/contracts/merge_requests.rake
!spec/contracts/provider/helpers/contract_source_helper.rb
# Require by db/fixtures/development/01_admin.rb
!spec/support/sidekiq_middleware.rb
ee/spec/
