import { GlSprintf } from '@gitlab/ui';
import Vue, { nextTick } from 'vue';
import Vuex from 'vuex';
import VueApollo from 'vue-apollo';
import TanukiBotChatApp from 'ee/ai/tanuki_bot/components/app.vue';
import AiGenieChat from 'ee/ai/components/ai_genie_chat.vue';
import { i18n } from 'ee/ai/constants';
import aiResponseSubscription from 'ee/graphql_shared/subscriptions/ai_completion_response.subscription.graphql';
import tanukiBotMutation from 'ee/ai/graphql/tanuki_bot.mutation.graphql';
import { shallowMountExtended } from 'helpers/vue_test_utils_helper';
import createMockApollo from 'helpers/mock_apollo_helper';
import { helpCenterState } from '~/super_sidebar/constants';
import {
  MOCK_USER_MESSAGE,
  MOCK_USER_ID,
  MOCK_TANUKI_SUCCESS_RES,
  MOCK_TANUKI_BOT_MUTATATION_RES,
} from '../mock_data';

Vue.use(Vuex);
Vue.use(VueApollo);

describe('TanukiBotChatApp', () => {
  let wrapper;

  const actionSpies = {
    sendUserMessage: jest.fn(),
    receiveTanukiBotMessage: jest.fn(),
    tanukiBotMessageError: jest.fn(),
  };

  let subscriptionHandlerMock = jest.fn().mockResolvedValue(MOCK_TANUKI_SUCCESS_RES);
  let mutationHandlerMock = jest.fn().mockResolvedValue(MOCK_TANUKI_BOT_MUTATATION_RES);

  const createComponent = () => {
    const store = new Vuex.Store({
      actions: actionSpies,
    });

    const apolloProvider = createMockApollo([
      [aiResponseSubscription, subscriptionHandlerMock],
      [tanukiBotMutation, mutationHandlerMock],
    ]);

    wrapper = shallowMountExtended(TanukiBotChatApp, {
      store,
      apolloProvider,
      propsData: {
        userId: MOCK_USER_ID,
      },
      stubs: {
        AiGenieChat,
        GlSprintf,
      },
    });
  };

  const findChatBackdrop = () => wrapper.findByTestId('tanuki-bot-chat-drawer-backdrop');
  const findWarning = () => wrapper.findByTestId('chat-legal-warning');
  const findGenieChat = () => wrapper.findComponent(AiGenieChat);
  const findGeneratedByAI = () => wrapper.findByText(i18n.GENIE_CHAT_LEGAL_GENERATED_BY_AI);

  describe('rendering', () => {
    beforeEach(() => {
      createComponent();
      helpCenterState.showTanukiBotChatDrawer = true;
    });

    it('renders a legal info when rendered', () => {
      expect(findWarning().exists()).toBe(true);
    });

    it('renders a generated by AI note', () => {
      expect(findGeneratedByAI().exists()).toBe(true);
    });

    it('renders the example question', () => {
      expect(wrapper.findByText('what is a fork').exists()).toBe(true);
    });
  });

  describe('AiGenieChat interactions', () => {
    beforeEach(() => {
      createComponent();
      helpCenterState.showTanukiBotChatDrawer = true;
    });

    it('closes the chat and the backdrop on @chat-hidden', async () => {
      findGenieChat().vm.$emit('chat-hidden');
      await nextTick();
      expect(helpCenterState.showTanukiBotChatDrawer).toBe(false);
      expect(findChatBackdrop().exists()).toBe(false);
      expect(findGenieChat().exists()).toBe(false);
    });
  });

  describe('The backdrop', () => {
    beforeEach(() => {
      createComponent();
    });

    it('is not rendered when the chat is closed', () => {
      expect(findChatBackdrop().exists()).toBe(false);
    });

    describe('when chat is opened', () => {
      beforeEach(() => {
        createComponent();
        helpCenterState.showTanukiBotChatDrawer = true;
      });

      it('is rendered', () => {
        expect(findChatBackdrop().exists()).toBe(true);
      });

      it('calls `closeDrawer` when clicked', async () => {
        findChatBackdrop().trigger('click');

        await nextTick();

        expect(findGenieChat().exists()).toBe(false);
      });
    });
  });

  describe('Chat', () => {
    beforeEach(() => {
      createComponent();
      helpCenterState.showTanukiBotChatDrawer = true;
    });

    it('renders AiGenieChat component', () => {
      expect(findGenieChat().exists()).toBe(true);
    });

    describe('when input is submitted', () => {
      beforeEach(() => {
        findGenieChat().vm.$emit('send-chat-prompt', MOCK_USER_MESSAGE.msg);
      });

      it('calls sendUserMessage when input is submitted', () => {
        expect(actionSpies.sendUserMessage).toHaveBeenCalledWith(
          expect.any(Object),
          MOCK_USER_MESSAGE.msg,
        );
      });

      it('calls GraphQL mutation when input is submitted', () => {
        expect(mutationHandlerMock).toHaveBeenCalledWith({
          resourceId: MOCK_USER_ID,
          question: MOCK_USER_MESSAGE.msg,
        });
      });

      it('once response arrives via GraphQL subscription calls receiveTanukiBotMessage', () => {
        expect(subscriptionHandlerMock).toHaveBeenCalledWith({
          resourceId: MOCK_USER_ID,
          userId: MOCK_USER_ID,
        });
        expect(actionSpies.receiveTanukiBotMessage).toHaveBeenCalledWith(
          expect.any(Object),
          MOCK_TANUKI_SUCCESS_RES.data,
        );
      });
    });
  });

  describe('Error conditions', () => {
    describe('when subscription fails', () => {
      beforeEach(async () => {
        subscriptionHandlerMock = jest.fn().mockRejectedValue({ errors: [] });
        createComponent();

        helpCenterState.showTanukiBotChatDrawer = true;
        await nextTick();
        findGenieChat().vm.$emit('send-chat-prompt', MOCK_USER_MESSAGE.msg);
      });

      it('once error arrives via GraphQL subscription calls tanukiBotMessageError', () => {
        expect(subscriptionHandlerMock).toHaveBeenCalledWith({
          resourceId: MOCK_USER_ID,
          userId: MOCK_USER_ID,
        });
        expect(actionSpies.tanukiBotMessageError).toHaveBeenCalled();
      });
    });

    describe('when mutation fails', () => {
      beforeEach(async () => {
        mutationHandlerMock = jest.fn().mockRejectedValue();
        createComponent();

        helpCenterState.showTanukiBotChatDrawer = true;
        await nextTick();
        findGenieChat().vm.$emit('send-chat-prompt', MOCK_USER_MESSAGE.msg);
      });

      it('calls tanukiBotMessageError', () => {
        expect(actionSpies.tanukiBotMessageError).toHaveBeenCalled();
      });
    });
  });
});
